backend = "glx";
vsync = true;

# --- Radius ---
corner-radius = 0;

# --- Shadows  ---
shadow = true;
shadow-radius = 20;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.5;
shadow-color = "#001a33"; 

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Polybar'",
  "class_g = 'i3-frame'",
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

# --- Animations ---
animations = true;
animation-stiffness = 250;
animation-dampening = 25;
animation-window-mass = 0.7;

# --- Fading ---
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;
